# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 16:32
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0007_auto_20160314_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
