# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 18:18
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blogengine', '0009_auto_20160331_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
