# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0010_auto_20160404_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='coverphoto',
            field=models.ImageField(default='coverphoto/None/no-img.jpg', upload_to='coverphoto/'),
        ),
    ]
